const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const RAW='https://raw.githubusercontent.com/franciscorestrepo-lang/ceo-lifeos/main';
const state={data:null,status:null,objectiveMode:'annual',lastGeneratedAt:null,pollTimer:null};
let deferredPrompt=null;

const REFRESH_COMMAND=`Ejecuta AHORA la revisión CEO LifeOS en Fase 1 usando los conectores ya autorizados en ChatGPT. Analiza como mínimo los últimos 30 días de Outlook (recibidos, enviados y todos los correos con bandera relevantes), Microsoft Teams, Read AI y Calendar; revisa además los próximos 30 días del calendario. Separa estrictamente AllUp, Teky, Sports Crowd y Personal/CEO. Deduplica compromisos entre fuentes. Prioriza caja, margen, cliente, producto, delivery, riesgo, delegación y capacidad real. Genera máximo 5 resultados críticos, 5 decisiones y 7 acciones personales. Trabajo propio de Francisco -> propuestas de calendario. Trabajo operativo -> delegación y propuestas de correo. NO envíes correos y NO crees eventos durante esta revisión. Compara con el estado anterior y marca NEW, IMPROVED, WORSENED, UNCHANGED o CLOSED. Actualiza directamente en GitHub el repositorio franciscorestrepo-lang/ceo-lifeos rama main: data/current.json, data/status.json, data/weekly/YYYY-Www.json, data/monthly/YYYY-MM.json y data/annual/YYYY.json. data/status.json debe terminar en READY e incluir generated_at, period, source_health y commit_sha. No cambies el código de la PWA. Verifica que current.json tenga contenido no vacío en critical_outcomes, decisions, my_actions y source_health. Al terminar confirma el commit y el deploy de Netlify.`;

function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function badge(v='P2'){return `<span class="badge ${String(v).toLowerCase()}">${esc(v)}</span>`}
function statusBadge(v='AT_RISK'){return `<span class="badge ${String(v).toLowerCase()}">${esc(v)}</span>`}
function item(title,meta='',right='',cls=''){return `<article class="item ${cls}"><div class="item-row"><div><div class="item-title">${esc(title)}</div><div class="item-meta">${esc(meta)}</div></div>${right}</div></article>`}
function metric(label,val){return `<div class="metric"><strong>${esc(val)}</strong><span>${esc(label)}</span></div>`}
function selected(kind){return $$(`input[data-kind="${kind}"]:checked`).map(x=>Number(x.dataset.index))}
function selectable(kind,i,title,meta,p){return `<article class="item"><label class="check"><input type="checkbox" data-kind="${kind}" data-index="${i}"/><div style="flex:1"><div class="item-row"><div><div class="item-title">${esc(title)}</div><div class="item-meta">${esc(meta)}</div></div>${badge(p)}</div></div></label></article>`}
function setSync(x){$('#syncStatus').textContent=x}
function validData(d){return d&&Array.isArray(d.critical_outcomes)&&d.critical_outcomes.length>0&&Array.isArray(d.decisions)&&d.decisions.length>0&&Array.isArray(d.my_actions)&&d.my_actions.length>0}

async function fetchJson(path){const urls=[`${RAW}/${path}?t=${Date.now()}`,`/${path}?t=${Date.now()}`];let last;for(const url of urls){try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status}`);return await r.json()}catch(e){last=e}}throw last}
async function loadStatus(){try{state.status=await fetchJson('data/status.json');renderPublishStatus()}catch{state.status=null;renderPublishStatus()}}
async function loadCurrent(show=true){try{const d=await fetchJson('data/current.json');if(!validData(d))throw new Error('current.json inválido o vacío');const previous=state.lastGeneratedAt;state.data=d;state.lastGeneratedAt=d.meta?.generated_at||null;render();await loadStatus();if(show)setSync(`Actualizado ${formatDate(d.meta?.generated_at)} · ${d.meta?.period||''}`);return previous!==state.lastGeneratedAt}catch(e){setSync(`Error leyendo GitHub: ${e.message}`);return false}}
function formatDate(v){if(!v)return 'sin fecha';try{return new Date(v).toLocaleString('es-CO',{dateStyle:'short',timeStyle:'short'})}catch{return v}}

async function copyAndOpen(command){try{await navigator.clipboard.writeText(command)}catch{}$('#commandPreview').value=command;$('#chatgptDialog').showModal()}
async function startRefresh(){await copyAndOpen(REFRESH_COMMAND);startPolling()}
function startPolling(){clearInterval(state.pollTimer);let attempts=0;setSync('Esperando nueva publicación de ChatGPT…');state.pollTimer=setInterval(async()=>{attempts++;const changed=await loadCurrent(false);if(changed){clearInterval(state.pollTimer);setSync(`Nueva revisión detectada · ${formatDate(state.lastGeneratedAt)}`)}else if(attempts>=40){clearInterval(state.pollTimer);setSync('Sin cambio todavía. Pulsa Verificar cuando ChatGPT termine.')}},15000)}
function openChatGPT(e){e?.preventDefault();window.open('https://chatgpt.com/','_blank','noopener')}

function render(){const d=state.data;if(!d)return;$('#weekLabel').textContent=d.meta?.period||'Semana';$('#lifeosStatus').textContent=d.meta?.status||d.capacity?.status||'AT_RISK';$('#lifeosScore').textContent=d.meta?.score??'—';$('#executiveSummary').textContent=d.meta?.executive_summary||'Panorama actualizado.';const hm=[['Resultados',d.critical_outcomes?.length||0],['Decisiones',d.decisions?.length||0],['Mis acciones',d.my_actions?.length||0],['Delegadas',d.delegated_actions?.length||0]];$('#headlineMetrics').innerHTML=hm.map(x=>metric(x[0],x[1])).join('');
 const monthly=d.monthly||[];const mp=monthly.length?Math.round(monthly.reduce((a,x)=>a+(x.progress??0),0)/monthly.length):0;$('#monthHeadline').textContent=`${monthly.length} objetivos mensuales`;$('#monthSummary').textContent=monthly.length?`${monthly.filter(x=>x.status==='OFF_TRACK').length} fuera de trayectoria; ${monthly.filter(x=>x.status==='AT_RISK').length} en riesgo.`:'Sin objetivos mensuales';$('#monthProgress').style.width=`${Math.min(100,mp)}%`;$('#monthKpis').innerHTML=[['Progreso',`${mp}%`],['Off track',monthly.filter(x=>x.status==='OFF_TRACK').length]].map(x=>metric(x[0],x[1])).join('');
 $('#criticalOutcomes').innerHTML=(d.critical_outcomes||[]).map(x=>item(x.title,`${x.company} · ${x.metric||x.expected_result||''}`,badge(x.priority))).join('');$('#companyCards').innerHTML=(d.companies||[]).map(c=>`<article class="company-card"><div class="item-row"><div><div class="eyebrow">${esc(c.name)}</div><h4>${esc(c.weekly_result||c.main_objective||'')}</h4></div>${statusBadge(c.status)}</div><p class="item-meta">${esc(c.main_risk||'')}</p><div class="tiny-progress"><span style="width:${Math.min(100,c.progress||0)}%"></span></div></article>`).join('');const nd=(d.decisions||[])[0];$('#nextDecision').innerHTML=nd?item(nd.decision,`${nd.company} · ${nd.deadline||''} · ${nd.recommendation||''}`,badge(nd.priority)):item('Sin decisión crítica','');const c=d.capacity||{};$('#capacityCard').innerHTML=item(`Estado: ${c.status||'—'}`,`Reuniones ${c.meeting_hours||0}h · CEO ${c.proposed_ceo_hours||0}h · Buffer ${c.buffer_hours||0}h`);
 renderObjectives();$('#myActions').innerHTML=(d.my_actions||[]).map(x=>item(x.action,`${x.company} · ${x.deadline||''} · ${x.estimated_minutes||0} min`,badge(x.priority))).join('');$('#decisions').innerHTML=(d.decisions||[]).map(x=>item(x.decision,`${x.company} · ${x.deadline||''} · ${x.recommendation||''}`,badge(x.priority))).join('');$('#calendarProposals').innerHTML=(d.calendar_proposals||[]).map((x,i)=>selectable('cal',i,x.title||`CAL-${String(i+1).padStart(2,'0')}`,`${x.company} · ${x.start||''} → ${x.end||''} · ${x.objective||''}`,x.priority)).join('')||item('Sin bloques propuestos','');$('#delegatedActions').innerHTML=(d.delegated_actions||[]).map(x=>item(x.activity,`${x.company} → ${x.responsible||'RESPONSABLE POR DEFINIR'} · ${x.deadline||''} · DoD: ${x.definition_of_done||''}`,badge(x.priority))).join('');$('#emailProposals').innerHTML=(d.email_proposals||[]).map((x,i)=>selectable('mail',i,x.subject||`MAIL-${String(i+1).padStart(2,'0')}`,`${x.company} · Para: ${(x.to||[]).join(', ')} · ${x.objective||''}`,x.priority)).join('')||item('Sin correos propuestos','');$('#risks').innerHTML=(d.risks||[]).map(x=>item(x.risk,`${x.company} · ${x.probability||''}/${x.impact||''} · ${x.mitigation||''}`,badge(x.priority),['HIGH','CRITICAL'].includes(x.impact)?'heat-high':x.impact==='MEDIUM'?'heat-medium':'heat-low')).join('');$('#flagged').innerHTML=(d.flagged||[]).map(x=>item(x.subject,`${x.classification||''} · ${x.recommendation||''}`,statusBadge(x.classification||'FOLLOW_UP'))).join('');renderSourceHealth();renderAlerts();}
function renderObjectives(){const list=state.data?.[state.objectiveMode]||[];$('#objectivesList').innerHTML=list.map(o=>`<article class="item"><div class="item-row"><div><div class="item-title">${esc(o.title||o.expected_result||'')}</div><div class="item-meta">${esc(o.company||'')} · ${esc(o.metric||'')} · ${esc(o.current??'')} / ${esc(o.target??'')}</div></div>${statusBadge(o.status||'AT_RISK')}</div><div class="objective-progress"><div class="tiny-progress"><span style="width:${Math.min(100,o.progress||0)}%"></span></div><strong>${Math.round(o.progress||0)}%</strong></div></article>`).join('')||item('Sin objetivos definidos','')}
function renderSourceHealth(){const h=state.data?.source_health||{};const ok=v=>['OK','SNAPSHOT','CONNECTED'].includes(String(v).toUpperCase());$('#sourceStrip').innerHTML=Object.entries(h).map(([k,v])=>`<span class="source-pill ${ok(v)?'ok':'warn'}">${esc(k)} · ${esc(String(v).toUpperCase())}</span>`).join('');$('#sourceHealth').innerHTML=Object.entries(h).map(([k,v])=>item(k,String(v))).join('')}
function renderPublishStatus(){const s=state.status;if(!s){$('#publishStatus').innerHTML=item('GitHub','status.json no disponible');return}$('#publishStatus').innerHTML=[item('Estado',s.status||'UNKNOWN'),item('Última publicación',formatDate(s.generated_at)),item('Periodo',s.period||''),item('Commit',s.commit_sha||'pendiente')].join('')}
function renderAlerts(){const alerts=[];for(const r of (state.data?.risks||[]).filter(x=>['P0','P1'].includes(x.priority)).slice(0,3))alerts.push(`<span class="alert-chip ${r.priority==='P0'?'red':'amber'}">${esc(r.company)} · ${esc(r.risk)}</span>`);$('#quickAlerts').innerHTML=alerts.join('')}
function doSearch(){const q=$('#globalSearch').value.trim().toLowerCase();if(!q)return;const groups=['annual','monthly','weekly','decisions','my_actions','delegated_actions','risks','flagged','email_proposals','calendar_proposals'];const hits=[];for(const g of groups)for(const x of(state.data?.[g]||[]))if(JSON.stringify(x).toLowerCase().includes(q))hits.push({g,x});$('#searchResults').innerHTML=hits.slice(0,30).map(h=>item(h.x.title||h.x.subject||h.x.decision||h.x.action||h.x.activity||h.x.risk||h.g,h.g)).join('')||item('Sin resultados',q)}
function approvalCommand(kind){const ids=selected(kind);if(!ids.length)return null;const arr=kind==='cal'?state.data.calendar_proposals:state.data.email_proposals;const prefix=kind==='cal'?'APROBAR CALENDARIO':'APROBAR CORREOS';const details=ids.map((i,n)=>`${kind==='cal'?'CAL':'MAIL'}-${String(i+1).padStart(2,'0')}: ${arr[i]?.title||arr[i]?.subject||''}`).join('\n');return `${prefix}: ${ids.map(i=>`${kind==='cal'?'CAL':'MAIL'}-${String(i+1).padStart(2,'0')}`).join(', ')}\n\nEjecuta estos elementos usando los conectores ya autorizados en ChatGPT. Calendario: verifica disponibilidad y crea solo los eventos aprobados, sin asistentes nuevos. Correos: crea borradores en Outlook, NO envíes.\n\n${details}`}
async function approve(kind){const cmd=approvalCommand(kind);if(!cmd)return alert('Selecciona al menos un elemento.');await copyAndOpen(cmd)}
function wire(){ $$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active')});$$('.segment').forEach(b=>b.onclick=()=>{$$('.segment').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.objectiveMode=b.dataset.objective;renderObjectives()});$('#refreshBtn').onclick=startRefresh;$('#checkBtn').onclick=()=>loadCurrent(true);$('#approveCalendarBtn').onclick=()=>approve('cal');$('#approveEmailsBtn').onclick=()=>approve('mail');$('#searchBtn').onclick=doSearch;$('#globalSearch').onkeydown=e=>{if(e.key==='Enter')doSearch()};$('#openChatGPTBtn').onclick=openChatGPT;window.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')loadCurrent(false)});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{await deferredPrompt?.prompt();deferredPrompt=null;$('#installBtn').classList.add('hidden')}}
wire();if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');loadCurrent(true);
