const SYSTEM=`Actúa como Chief of Staff, CFO, CCO, CPO/CTO y operador senior de Francisco. Separa estrictamente AllUp, Teky, Sports Crowd y Personal. Prioriza caja, margen, cliente, producto, ejecución, riesgo, delegación y capacidad. Máximo 5 resultados críticos semanales, 5 decisiones y 7 acciones personales. Las tareas personales deben ser solo decidir, aprobar, negociar, relacionarse, desbloquear o definir dirección. Todo lo operativo debe delegarse. Da prioridad superior a correos con bandera. Deduplica compromisos entre Outlook, Calendar, Teams y Read AI. No inventes responsables, emails, fechas contractuales ni hechos. Usa solo responsables y direcciones presentes en datos. Mantén 30% de buffer ejecutivo y no propongas bloques de calendario que pisen reuniones. Clasifica correos con bandera como CEO_DECISION, DELEGATE, WAITING, FOLLOW_UP o CLOSE_FLAG. Devuelve JSON estricto.`;

const schema={type:'object',additionalProperties:false,required:['meta','annual','monthly','weekly','companies','critical_outcomes','decisions','my_actions','delegated_actions','calendar_proposals','email_proposals','risks','flagged','capacity','source_health','evolution'],properties:{
 meta:{type:'object',additionalProperties:false,required:['generated_at','period','status','score','executive_summary','mode','version'],properties:{generated_at:{type:['string','null']},period:{type:'string'},status:{type:'string'},score:{type:'number'},executive_summary:{type:'string'},mode:{type:'string'},version:{type:'number'}}},
 annual:{type:'array',items:{$ref:'#/$defs/objective'}},monthly:{type:'array',items:{$ref:'#/$defs/objective'}},weekly:{type:'array',items:{$ref:'#/$defs/objective'}},
 companies:{type:'array',items:{type:'object',additionalProperties:false,required:['name','status','progress','main_objective','main_risk','weekly_result'],properties:{name:{type:'string'},status:{type:'string'},progress:{type:'number'},main_objective:{type:'string'},main_risk:{type:'string'},weekly_result:{type:'string'}}}},
 critical_outcomes:{type:'array',maxItems:5,items:{type:'object',additionalProperties:false,required:['id','company','priority','title','expected_result','metric','deadline','owner','status','confidence','sources'],properties:{id:{type:'string'},company:{type:'string'},priority:{type:'string'},title:{type:'string'},expected_result:{type:'string'},metric:{type:'string'},deadline:{type:'string'},owner:{type:'string'},status:{type:'string'},confidence:{type:'number'},sources:{type:'array',items:{$ref:'#/$defs/source'}}}}},
 decisions:{type:'array',maxItems:5,items:{type:'object',additionalProperties:false,required:['id','company','priority','decision','deadline','impact','options','recommendation','information_missing','sources'],properties:{id:{type:'string'},company:{type:'string'},priority:{type:'string'},decision:{type:'string'},deadline:{type:'string'},impact:{type:'string'},options:{type:'array',items:{type:'string'}},recommendation:{type:'string'},information_missing:{type:'string'},sources:{type:'array',items:{$ref:'#/$defs/source'}}}}},
 my_actions:{type:'array',maxItems:7,items:{type:'object',additionalProperties:false,required:['id','company','priority','action','deadline','expected_result','estimated_minutes','sources'],properties:{id:{type:'string'},company:{type:'string'},priority:{type:'string'},action:{type:'string'},deadline:{type:'string'},expected_result:{type:'string'},estimated_minutes:{type:'number'},sources:{type:'array',items:{$ref:'#/$defs/source'}}}}},
 delegated_actions:{type:'array',items:{type:'object',additionalProperties:false,required:['id','company','priority','responsible','activity','expected_result','deadline','definition_of_done','metric','dependency','sources'],properties:{id:{type:'string'},company:{type:'string'},priority:{type:'string'},responsible:{type:'string'},activity:{type:'string'},expected_result:{type:'string'},deadline:{type:'string'},definition_of_done:{type:'string'},metric:{type:'string'},dependency:{type:'string'},sources:{type:'array',items:{$ref:'#/$defs/source'}}}}},
 calendar_proposals:{type:'array',items:{type:'object',additionalProperties:false,required:['id','company','priority','title','start','end','objective','description','sources'],properties:{id:{type:'string'},company:{type:'string'},priority:{type:'string'},title:{type:'string'},start:{type:'string'},end:{type:'string'},objective:{type:'string'},description:{type:'string'},sources:{type:'array',items:{$ref:'#/$defs/source'}}}}},
 email_proposals:{type:'array',items:{type:'object',additionalProperties:false,required:['id','company','priority','to','cc','subject','objective','body','sources'],properties:{id:{type:'string'},company:{type:'string'},priority:{type:'string'},to:{type:'array',items:{type:'string'}},cc:{type:'array',items:{type:'string'}},subject:{type:'string'},objective:{type:'string'},body:{type:'string'},sources:{type:'array',items:{$ref:'#/$defs/source'}}}}},
 risks:{type:'array',items:{type:'object',additionalProperties:false,required:['id','company','priority','category','risk','probability','impact','mitigation','owner','sources'],properties:{id:{type:'string'},company:{type:'string'},priority:{type:'string'},category:{type:'string'},risk:{type:'string'},probability:{type:'string'},impact:{type:'string'},mitigation:{type:'string'},owner:{type:'string'},sources:{type:'array',items:{$ref:'#/$defs/source'}}}}},
 flagged:{type:'array',items:{type:'object',additionalProperties:false,required:['id','subject','classification','recommendation','source_url'],properties:{id:{type:'string'},subject:{type:'string'},classification:{type:'string'},recommendation:{type:'string'},source_url:{type:'string'}}}},
 capacity:{type:'object',additionalProperties:false,required:['calendar_hours','meeting_hours','proposed_ceo_hours','buffer_hours','status'],properties:{calendar_hours:{type:'number'},meeting_hours:{type:'number'},proposed_ceo_hours:{type:'number'},buffer_hours:{type:'number'},status:{type:'string'}}},
 source_health:{type:'object',additionalProperties:false,required:['mail','flagged','calendar','teams','read'],properties:{mail:{type:'string'},flagged:{type:'string'},calendar:{type:'string'},teams:{type:'string'},read:{type:'string'}}},
 evolution:{type:'object',additionalProperties:false,required:['new','improved','worsened','unchanged','closed'],properties:{new:{type:'array',items:{type:'string'}},improved:{type:'array',items:{type:'string'}},worsened:{type:'array',items:{type:'string'}},unchanged:{type:'array',items:{type:'string'}},closed:{type:'array',items:{type:'string'}}}}
},$defs:{source:{type:'object',additionalProperties:false,required:['type','id','url'],properties:{type:{type:'string'},id:{type:'string'},url:{type:'string'}}},objective:{type:'object',additionalProperties:false,required:['id','company','title','description','metric','target','current','unit','progress','status','deadline','owner','confidence','notes'],properties:{id:{type:'string'},company:{type:'string'},title:{type:'string'},description:{type:'string'},metric:{type:'string'},target:{type:['number','string']},current:{type:['number','string']},unit:{type:'string'},progress:{type:'number'},status:{type:'string'},deadline:{type:'string'},owner:{type:'string'},confidence:{type:'number'},notes:{type:'string'}}}}};

function userPrompt({now,microsoft,read,previous,mode='manual'}){return `${SYSTEM}\nFecha actual: ${now}. Modo: ${mode}. Analiza mínimo 30 días y próximos 30 días del calendario. Para objetivos anuales/mensuales: conserva objetivos explícitos de previous si existen; no inventes metas numéricas. Si no hay meta confirmada, usa texto 'POR DEFINIR' y progreso 0. Compara con previous para evolution. Los correos con bandera pueden ser antiguos, pero solo conserva los relevantes. No uses Monday. Genera propuestas de calendario y email, pero no ejecutes. DATA MICROSOFT:\n${JSON.stringify(microsoft||{}).slice(0,650000)}\nDATA READ:\n${JSON.stringify(read||{}).slice(0,250000)}\nPREVIOUS:\n${JSON.stringify(previous||{}).slice(0,180000)}`}

async function openaiAnalyze(payload){const key=process.env.OPENAI_API_KEY;if(!key)throw new Error('OPENAI_API_KEY missing');const model=process.env.OPENAI_MODEL||'gpt-5.2';const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model,input:userPrompt(payload),text:{format:{type:'json_schema',name:'ceo_lifeos',schema,strict:true}}})});if(!r.ok)throw new Error(`OpenAI ${r.status}: ${await r.text()}`);const j=await r.json();let text=j.output_text||'';if(!text)text=(j.output||[]).flatMap(x=>x.content||[]).map(x=>x.text||'').join('');return JSON.parse(text)}
async function anthropicAnalyze(payload){const key=process.env.ANTHROPIC_API_KEY;if(!key)throw new Error('ANTHROPIC_API_KEY missing');const model=process.env.ANTHROPIC_MODEL||'claude-sonnet-4-5';const prompt=`${userPrompt(payload)}\nDevuelve exclusivamente JSON que siga este JSON Schema:\n${JSON.stringify(schema)}`;const r=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'x-api-key':key,'anthropic-version':'2023-06-01','content-type':'application/json'},body:JSON.stringify({model,max_tokens:16000,messages:[{role:'user',content:prompt}]})});if(!r.ok)throw new Error(`Anthropic ${r.status}: ${await r.text()}`);const j=await r.json();const text=(j.content||[]).filter(x=>x.type==='text').map(x=>x.text).join('');const clean=text.replace(/^```json\s*/,'').replace(/```$/,'').trim();return JSON.parse(clean)}
export async function analyzeExecutiveContext(payload){const provider=(process.env.AI_PROVIDER||'openai').toLowerCase();const result=provider==='anthropic'?await anthropicAnalyze(payload):await openaiAnalyze(payload);result.meta={...(result.meta||{}),generated_at:new Date().toISOString(),mode:payload.mode||'manual',version:1};return result}
export {schema};
